### ISSUE TITLE
Upgrading to monaco 0.9.0 breaks editor

### ISSUE THREAD

**Issue by anandanand84** [paulvarache/monaco-editor-element#1]
I tried to upgrade to latest version of monaco editor 0.9.0 and ran ./build.sh, when I tried the demo.html, it loads the editor but could not edit anything

**Comment by paulvarache** [comment]
Thanks for reporting, I did the changes to support 0.9.0 in https://github.com/paulvarache/monaco-editor-element/pull/2. Let me know if anything is not working
